name: Enviar Notificación a ntfy.sh

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificación a ntfy.sh
        run: |
          curl -d "✅ Código actualizado en la rama main - DevOps ITLA" https://ntfy.sh/devops-itla
